import { ApplicationHeader } from "../components/ApplicationHeader"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ApplicationHeader,
  "https://www.figma.com/design/AWJRWAHO9CrLLUQJzoN4xs/iX-Components---v3.0-Original?node-id=47750-30684",
  {
    props: {
      appName: figma.string("appName"),
      avatar: figma.boolean("avatar"),
      appSwitch: figma.boolean("appSwitch"),
      children: figma.children("Avatar"),
    },
    example: (props) => (
      <ApplicationHeader 
        appName={props.appName}
        avatar={props.avatar}
        appSwitch={props.appSwitch}
      >
        {props.children}
      </ApplicationHeader>
    ),
  },
)
