import { Button } from "../components/Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/AWJRWAHO9CrLLUQJzoN4xs/iX-Components---v3.0-Original?node-id=47170-11176",
  {
    props: {
      variant:figma.enum('variant',{
        'Primary':'Primary',
        'Primary outline':'Primary outline',
        'Primary ghost':'Primary ghost',
        'Secondary':'Secondary',
        'Secondary outline':'Secondary outline',
        'Secondary ghost':'Secondary ghost',
        'Danger':'Danger',
        'Danger outline':'Danger outline',
        'Danger ghost':'Danger ghost'
      }),
      defaultSlot: figma.string("defaultSlot"),
      showIcon: figma.boolean("Show icon"),
      nestedIcon: figma.nestedProps("Icon",{
        name:figma.string('Name')
      }),
      disabled:figma.boolean('disabled')
    },
    example: (props) => (
      <Button
        variant={props.variant}
        showIcon={props.showIcon}
        icon={props.nestedIcon.name}
        disabled={props.disabled}
      >
        {props.defaultSlot}
      </Button>
      ),
  },
)
