import { Cardcontainer } from "../components/Cardcontainer"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Cardcontainer,
  "https://www.figma.com/design/AWJRWAHO9CrLLUQJzoN4xs/iX-Components---v3.0-Original?node-id=47166-16447",
  {
    props: {
      focused: figma.boolean("Focused"),
      selected: figma.boolean('selected'),
      children: figma.children("*"),
    },
    example: (props) => (
      <Cardcontainer 
        focused={props.focused}
        selected={props.selected}
      >
        {props.children}
      </Cardcontainer>
    ),
  },
)
