import { ContentHeader } from "../components/ContentHeader"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ContentHeader,
  "https://www.figma.com/design/AWJRWAHO9CrLLUQJzoN4xs/iX-Components---v3.0-Original?node-id=47715-1590",
  {
    props: {
      showHeaderSubtitle: figma.boolean("Show header subtitle"),
      showActionsSlot: figma.boolean("showActionsSlot"),
      hasBackButton: figma.boolean("Has back button"),
      headerTitle: figma.string("Header title"),
      headerSubtitle: figma.string("Header subtitle"),
      variant: figma.enum('Variant', {
        Primary: 'Primary',
        Secondary: 'Secondary'
      }),
      actionsSlot: figma.children('*')
    },
    example: (props) => (
      <ContentHeader
        headerTitle={props.headerTitle}
        headerSubtitle={props.headerSubtitle}
        showHeaderSubtitle={props.showHeaderSubtitle}
        hasBackButton={props.hasBackButton}
        buttonSlot={props.showActionsSlot}
        variant={props.variant}
      >
        {props.actionsSlot}
      </ContentHeader>
    ),
  },
)
