import { EventListItem } from "../components/EventListItem"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  EventListItem,
  "https://www.figma.com/design/AWJRWAHO9CrLLUQJzoN4xs/iX-Components---v3.0-Original?node-id=47166-16379",
  {
    props: {
      chevron: figma.boolean("Chevron"),
      focused: figma.boolean("Focused"),
      nestedSeverity:figma.nestedProps('_Severity Indicator',{
        severitycolor:figma.enum('Item color',{
          '--theme-color-alarm':'alarm',
          '--theme-color-warning':'warning',
          '--theme-color-critical':'critical',
          '--theme-color-info':'info',
          '--theme-color-success':'success',
          '--theme-color-neutral':'neutral',
        })
      }),
      state:figma.enum('State',{
        Disabled:true
      }),
      contentSlot:figma.children('*')
    },
    example: (props) => (
      <EventListItem 
        chevron={props.chevron}
        disabled={props.state}
        severity={props.nestedSeverity.severitycolor}
      >
        {props.contentSlot}
      </EventListItem>
    ),
  },
)
