import { MenuItem } from "../components/MenuItem"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  MenuItem,
  "https://www.figma.com/design/AWJRWAHO9CrLLUQJzoN4xs/iX-Components---v3.0-Original?node-id=47166-16216",
  {
    props: {
      label: figma.string("Label"),
      focused: figma.boolean("Focused"),
      notification: figma.boolean("Notification"),
      nestedIcon:figma.nestedProps("Icon",{
        name:figma.string('Name')
      })
    },
    example: (props) => (
      <MenuItem 
        icon={props.nestedIcon.name}
        label={props.label}
      />
    ),
  },
)
