import { Tooltip } from "../components/Tooltip"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */ 

figma.connect(
  Tooltip,
  "https://www.figma.com/design/AWJRWAHO9CrLLUQJzoN4xs/iX-Components---v3.0-Original?node-id=48332-559595",
  {
    props: {
      closable: figma.boolean("Closable"),
      header: figma.string("header"),
      textlabel: figma.string("textlabel"),
      nestedIcon:figma.nestedProps('leftIcon',{
        name:figma.string('Name')
      })
    },
    example: (props) => (
      <Tooltip
        header={props.header}
        textlabel={props.textlabel}
        closable={props.closable}
        icon={props.nestedIcon.name}
      />),
  },
)
