// 可用图标列表（用于 Storybook）
export const availableIcons = [
  'home',
  'dashboard',
  'settings',
  'user',
  'user-management',
  'calendar',
  'clock',
  'search',
  'filter',
  'edit',
  'delete',
  'add',
  'remove',
  'save',
  'close',
  'check',
  'info',
  'warning',
  'error',
  'help',
  'menu',
  'more',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'arrow-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'chevron-down',
  'alarm-bell',
  'maintenance',
  'cogwheel',
] as const;

export type AvailableIcon = typeof availableIcons[number];
