// 可用图标列表（用于 Storybook）
// 这些图标都来自 @irisieason/ix-icons 包
export const availableIcons = [
  'home',
  'dashboard',
  'cogwheel',
  'user',
  'user-management',
  'calendar',
  'clock',
  'search',
  'filter',
  'edit-document',
  'trashcan',
  'add',
  'remove-circle',
  'disk',
  'close',
  'check',
  'info',
  'warning',
  'error',
  'help',
  'menu',
  'more-menu',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'arrow-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'chevron-down',
  'alarm-bell',
  'maintenance',
  'notification',
  'e-mail',
] as const;

export type AvailableIcon = typeof availableIcons[number];
