import { EventItemContent } from "../components/EventItemContent"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  EventItemContent,
  "https://www.figma.com/design/AWJRWAHO9CrLLUQJzoN4xs/iX-Components---v3.0-Original?node-id=47166-16416",
  {
    props: {
      header: figma.string("Header"),
      subheader: figma.string("Subheader"),
      subInfo: figma.string("Sub Info"),
      timestamp: figma.string("Timestamp"),
      disabled:figma.boolean('Disabled'),
      nestedicon:figma.nestedProps('lIcon',{
        name:figma.string('Name')
      }),
      nestediconbutton:figma.nestedProps('Icon',{
        name:figma.string('Name')
      }),
      nestedbuttonlabel:figma.nestedProps('Button',{
        label:figma.string('Label')
      }),
      showbutton:figma.boolean('showbutton')
    },
    example: (props) => (
      <EventItemContent 
        icon={props.nestedicon.name}
        header={props.header}
        subheader={props.subheader}
        subInfo={props.subInfo}
        timestamp={props.timestamp}
        disabled={props.disabled}
        iconButton={props.nestediconbutton.name}
        buttonLabel={props.nestedbuttonlabel.label}
        showButton={props.showbutton}
      />
    ),
  },
)
