import { MenuItemList } from "../components/MenuItemList"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  MenuItemList,
  "https://www.figma.com/design/AWJRWAHO9CrLLUQJzoN4xs/iX-Components---v3.0-Original?node-id=47822-2134",
  {
    props: {
      content: figma.children('MenuItem')
    },
    example: (props) => (
      <MenuItemList>
        {props.content}
      </MenuItemList>
      ),
  },
)
