/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * NOTE: This file is automatically generated from Figma Theme Variables.
 * Theme: Classic Dark (mode: 33940:4)
 * Do NOT edit this file directly — changes will be overwritten.
 */

export const colors = {
  // Background colors
  'color-0': 'rgba(0, 0, 0, 0)',
  'color-1': '#0f1619',
  'color-2': '#283236',
  'color-3': '#3c484d',
  'color-4': '#4c5a60',
  'color-5': '#59686f',
  'color-6': '#63737a',
  'color-7': '#6b7c85',
  'color-8': '#94a1a9',

  // Border colors
  'color-std-bdr': 'rgba(211, 237, 249, 0.55)',
  'color-soft-bdr': 'rgba(211, 237, 249, 0.4)',
  'color-weak-bdr': 'rgba(224, 245, 255, 0.25)',
  'color-x-weak-bdr': 'rgba(142, 157, 165, 0.2)',
  'color-focus-bdr': '#19a0ff',
  'color-contrast-bdr': '#ffffff',
  'color-hard-bdr': '#6b7c85',
  'color-alarm-bdr': '#ff2453',
  'color-warning-bdr': '#ffbb00',

  // Interactive - Ghost colors
  'color-ghost': 'rgba(166, 171, 140, 0)',
  'color-ghost--hover': 'rgba(140, 161, 171, 0.2)',
  'color-ghost--active': 'rgba(166, 171, 140, 0.15)',
  'color-ghost--selected': 'rgba(85, 255, 0, 0.1)',
  'color-ghost--selected-hover': 'rgba(154, 253, 104, 0.2)',
  'color-ghost--selected-active': 'rgba(151, 221, 115, 0.2)',
  'color-ghost-primary--active': 'rgba(43, 128, 0, 0.2)',
  'color-ghost-primary--hover': 'rgba(85, 255, 0, 0.15)',
  'color-ghost-alt': 'rgba(255, 255, 255, 0.05)',
  'color-ghost-alt--hover': 'rgba(140, 161, 171, 0.2)',
  'color-ghost-alt--active': 'rgba(140, 161, 171, 0.15)',
  'color-ghost-alt--selected': 'rgba(58, 255, 255, 0.15)',
  'color-ghost-alt--selected-hover': 'rgba(123, 253, 253, 0.25)',
  'color-ghost-alt--selected-active': 'rgba(115, 221, 221, 0.25)',

  // Interactive - Primary colors
  'color-primary': '#00bdff',
  'color-primary--contrast': '#000000',
  'color-primary--hover': '#1aecff',
  'color-primary--active': '#00eaff',
  'color-primary--disabled': 'rgba(0, 170, 204, 0.45)',

  // Interactive - Dynamic colors
  'color-dynamic': '#00eaff',
  'color-dynamic--hover': '#62e3ee',
  'color-dynamic--active': '#5cd5e0',
  'color-dynamic-alt': '#00eaff',
  'color-dynamic-alt--hover': '#62e3ee',
  'color-dynamic-alt--active': '#5cd5e0',

  // Interactive - Secondary colors
  'color-secondary': '#000000',
  'color-secondary--hover': '#002639',
  'color-secondary--active': '#001d2b',

  // Interactive - Component colors
  'color-component-1': 'rgba(140, 161, 171, 0.2)',
  'color-component-1--hover': 'rgba(140, 161, 171, 0.35)',
  'color-component-1--active': 'rgba(140, 161, 171, 0.25)',
  'color-component-2': 'rgba(211, 239, 253, 0.25)',
  'color-component-3': 'rgba(217, 243, 255, 0.4)',
  'color-component-4': 'rgba(215, 242, 255, 0.5)',
  'color-component-5': 'rgba(224, 245, 255, 0.6)',
  'color-component-6': 'rgba(217, 234, 242, 0.65)',
  'color-component-7': 'rgba(0, 234, 255, 0.15)',
  'color-component-7--hover': '#19626a',
  'color-component-7--active': '#165c62',
  'color-component-8': '#00273b',
  'color-component-8--hover': '#002639',
  'color-component-9': '#00eaff',
  'color-component-9--hover': '#52f1ff',
  'color-component-9--active': '#0aebff',
  'color-component-9--disabled': 'rgba(0, 234, 255, 0.3)',
  'color-component-10': 'rgba(0, 234, 255, 0.75)',
  'color-component-10--hover': 'rgba(107, 243, 253, 0.6)',
  'color-component-10--active': 'rgba(10, 235, 255, 0.75)',
  'color-component-10--disabled': 'rgba(0, 234, 255, 0.2)',
  'color-component-11': 'rgba(86, 97, 103, 0.2)',
  'color-component-error': '#310006',
  'color-component-warning': '#4b3e26',
  'color-component-info': '#001c4d',

  // Interactive - State colors
  'color-1--hover': '#283236',
  'color-1--active': '#222b30',

  // Status colors - Alarm
  'color-alarm': '#ff2453',
  'color-alarm--hover': '#ff577b',
  'color-alarm--active': '#ff335f',
  'color-alarm--contrast': '#000000',
  'color-alarm-40': 'rgba(255, 38, 85, 0.4)',
  'color-alarm-10': 'rgba(255, 38, 85, 0.1)',
  'color-alarm-20': 'rgba(255, 38, 85, 0.2)',

  // Status colors - Warning
  'color-warning': '#ffbb00',
  'color-warning--hover': '#ffc533',
  'color-warning--active': '#ffba0a',
  'color-warning--contrast': '#000000',
  'color-warning-40': 'rgba(255, 187, 0, 0.4)',
  'color-warning-20': 'rgba(255, 187, 0, 0.2)',
  'color-warning-10': 'rgba(255, 187, 0, 0.1)',

  // Status colors - Critical
  'color-critical': '#eb7a0a',
  'color-critical--hover': '#ed8721',
  'color-critical--active': '#eb8014',
  'color-critical--contrast': '#000000',
  'color-critical-40': 'rgba(235, 122, 10, 0.4)',

  // Status colors - Success
  'color-success': '#00cc5c',
  'color-success--hover': '#4eeb00',
  'color-success--active': '#47d700',
  'color-success--contrast': '#000000',
  'color-success-40': 'rgba(72, 215, 0, 0.4)',
  'color-success-20': 'rgba(72, 215, 0, 0.2)',

  // Status colors - Info
  'color-info': '#357fff',
  'color-info--hover': '#4d8eff',
  'color-info--active': '#3d84ff',
  'color-info--contrast': '#000000',
  'color-info-40': 'rgba(53, 127, 255, 0.4)',

  // Status colors - Neutral
  'color-neutral': '#b6b9ba',
  'color-neutral--hover': '#c9cbcb',
  'color-neutral--active': '#acafb0',
  'color-neutral--contrast': '#000000',
  'color-neutral-40': 'rgba(182, 185, 186, 0.4)',

  // Text colors
  'color-contrast-text': '#ffffff',
  'color-std-text': 'rgba(245, 252, 255, 0.9)',
  'color-soft-text': 'rgba(229, 247, 255, 0.65)',
  'color-weak-text': 'rgba(219, 244, 255, 0.4)',
  'color-inv-contrast-text': '#000000',
  'color-inv-std-text': 'rgba(0, 10, 20, 0.9)',
  'color-inv-soft-text': 'rgba(0, 13, 20, 0.6)',
  'color-inv-weak-text': 'rgba(0, 13, 20, 0.45)',
  'color-alarm-text': '#ff7694',

  // Effect colors
  'color-lightbox': 'rgba(0, 0, 0, 0.65)',
  'color-backdrop': 'rgba(0, 0, 0, 0.85)',
  'color-backdrop-3': 'rgba(55, 70, 77, 0.85)',

  // Shadow colors
  'color-shadow-1': 'rgba(0, 0, 0, 0.6)',
  'color-shadow-2': '#000000',
  'color-shadow-3': 'rgba(0, 0, 0, 0.6)',

  // Gradient colors
  'color-gradient-effect-1': '#1aecff',
  'color-gradient-effect-2': '#00bde3',

  // Logo colors
  'color-logo': '#ffffff',
  'color-logo-login': '#ffffff',

  // Chart colors
  'chart-1': '#00ffe7',
  'chart-1-40': 'rgba(0, 255, 231, 0.4)',
  'chart-2': '#94ffc9',
  'chart-2-40': 'rgba(148, 255, 201, 0.4)',
  'chart-3': '#00c2cc',
  'chart-3-40': 'rgba(0, 194, 204, 0.4)',
  'chart-4': '#a3eeff',
  'chart-4-40': 'rgba(163, 238, 255, 0.4)',
  'chart-5': '#90b4c5',
  'chart-5-40': 'rgba(144, 180, 197, 0.4)',
  'chart-6': '#42c6ff',
  'chart-6-40': 'rgba(66, 198, 255, 0.4)',
  'chart-7': '#7aaaff',
  'chart-7-40': 'rgba(122, 170, 255, 0.4)',
  'chart-8': '#9ebcff',
  'chart-8-40': 'rgba(158, 188, 255, 0.4)',
  'chart-9': '#9ea3ff',
  'chart-9-40': 'rgba(158, 163, 255, 0.4)',
  'chart-10': '#b999ff',
  'chart-10-40': 'rgba(185, 153, 255, 0.4)',
  'chart-11': '#d08fff',
  'chart-11-40': 'rgba(208, 143, 255, 0.4)',
  'chart-12': '#ed85ff',
  'chart-12-40': 'rgba(237, 133, 255, 0.4)',
  'chart-13': '#f38fc2',
  'chart-13-40': 'rgba(243, 143, 194, 0.4)',
  'chart-14': '#ef9a9a',
  'chart-14-40': 'rgba(239, 154, 154, 0.4)',
  'chart-15': '#ffb180',
  'chart-15-40': 'rgba(255, 177, 128, 0.4)',
  'chart-16': '#cacab4',
  'chart-16-40': 'rgba(202, 202, 180, 0.4)',
  'chart-17': '#b5bd00',
  'chart-17-40': 'rgba(181, 189, 0, 0.4)',

  // Chart infrastructure
  'chart-axes': 'rgba(255, 255, 255, 0.3)',
  'chart-grid-lines': 'rgba(255, 255, 255, 0.1)',
  'chart-grid-fill': '#23233c',
  'chart-ticks': 'rgba(255, 255, 255, 0.35)',
  'chart-tooltip-fill': 'rgba(15, 22, 25, 0.8)',
  'chart-tooltip-bdr': 'rgba(255, 255, 255, 0.25)',
} as const;

export type ColorToken = keyof typeof colors;
